FORMAT: 1A
HOST: http://itas.apiary.io/
VERSION: 1.0

# ITAS Invoicing 1.0

<br />
<strong>Release notes</strong> (XX<sup>st</sup> November 2022.)

## New Endpoints

<ul>
<li>Invoicing <b>Trade</b>: Create Sales Invoicing Pilot,<a href="/#reference/invoicing/create-sales"> Link</a></li>
<li>Invoicing <b>Manual</b>: Create Manual Invoicing,<a href="/#reference/invoicing/create-manual"> Link</a></li>
</ul>

## Updated Endpoints
<ul>
<li>None</li>
</ul>

## AccessToken [/]
Model Header containing AccessToken

+ Model 
    + Header

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

# Group Manual Invoicing
Manual Invoicing Processes

## Create Manual [/Invoicing/{TradingEntityId}/Manual/Invoice]
`POST` Manual Ivoice

### Create Manual Invoice [POST]

<b>Request Body</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|DocumentBody|see <b><a href="/#reference/data-object-definitions/documentbody/documentdetails">Document Body</a></b> object|`object`|||Required|
|AccountDetails|see <b><a href="/#reference/data-object-definitions/accountdetails">Account Details</a></b> object|[array] of `object`|||Required|

<hr />

<b>Response Data</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|InvoiceReference|Invoice Reference|`string`||||

+ Parameters
    + TradingEntityId (required, string, `JT`) ... Identify specific trading entity.

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Attributes (CreateManualInvoice)

+ Response 201 (application/json; charset=utf-8)
    + Attributes 
        + Data (InvoiceRefResponse)
        + Response (201 CreateResponse)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (405 Response)

# Group Trade Invoicing
Trade Invoicing Processes

## Create Sales [/Invoicing/{TradingEntityId}/Trade/Sales]
`POST` Sales Invoicing Pilot

### Create Sales Invoice [POST]

<b>Request Body</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ContractId|Contract ID|`string`|10||Required|
|InvoiceDate|Invoice Date|`datetime`|||Required|
|ValueDate|Value Date|`datetime`|||Required|
|Quantity|Quantity|`decimal`|||Required|
|InvoiceCurrencyCode|Invoice Currency Code|`string`|3||Required|
|InvoiceValue|Invoice Value|`decimal`|||Required|
|VatRateCode|Vat Rate Code|`string`|2||Required|
|VatValue|VAT Value|`decimal`|||Required|
|IsSecure|Is Secure|`boolean`||||
|PaymentMode|Payment Mode|`string`|1|||
|PaymentTermsCode|Payment Terms Code|`string`|8|||
|ClientReference|Client Reference|`string`|25|||
|Narrative|Narrative|`string`|30|||
|AuthoriseForPosting|Authorise For Posting|`boolean`||||
|Costs|see <b><a href="/#reference/data-object-definitions/cost/cost">Cost</a></b> object|[array] of `object`||||

<hr />

<b>Response Data</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|InvoiceReference|Invoice Reference|`string`||||

+ Parameters
    + TradingEntityId (required, string, `JT`) ... Identify specific trading entity.

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Attributes (CreateInvSales)

+ Response 201 (application/json; charset=utf-8)
    + Attributes 
        + Data (InvoiceRefResponse)
        + Response (201 CreateResponse)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (405 Response)


# Group Data Object Definitions
List of re-usable Data Objects referenced as `object` types. Not that these endpoints are not accessable and only here for reference purposes.

## AccountDetails [/AccountDetails]
A multipurpose object used by several endpoints
### AccountDetails[GET]


|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|AccountCode|Account Code|`string`|11||Required|
|AccountLedgerType|Account Ledger Type|`string`|1||Required. `C`, `N` or `K`|
|ExpenseCode|Expense Code|`string`|7||Required|
|DepartmentCode|Department Code|`string`|4||Required|
|AmountInDocumentCurrency|Amount in Document Currency|`decimal`||Can Contain Negative Values|Required|
|AmountInInvoiceCurrency|Amount in Invoice Currency|`decimal`||Can Contain Negative Values||
|AmountInFunctionalCurrency|Amount in Functional Currency|`decimal`||Can Contain Negative Values||
|VatCode|Vat Code|`string`|2|||
|Narrative|Narrative|`string`|30|||
|SecondaryReference|Secondary Reference|`string`|10|||
|Memo|Contract Reference|`string`|100|||
|FreeField|Client Reference|`string`|10|||
|PersonalInits|Client Reference|`string`|3|||


+ Response 200 (application/json; charset=utf-8)
+ Attributes (AccountDetailsVat)

## Cost [/Costs]
A multipurpose object used by several endpoints. 

### Cost[GET]

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|CostCode|Cost Code|`string`|8||Required|
|CurrencyCode|Currency Code|`string`|3||Required|
|ExpenseCode|Expense Code|`string`|7||Required|
|SupplierCode|Supplier Code|`string`|10||Required|
|CostValueInvoiceCcy|Cost Value in Invoice Ccy|`decimal`||Negative if Payable|Required|
|CostValueCostCcy|Cost Value in Cost Ccy|`decimal`||Negative if Payable|Required|


+ Response 200 (application/json; charset=utf-8)
+ Attributes (Cost)


## DocumentBody [/DocumentBody]
A multipurpose object used by several endpoints
### DocumentBody[GET]


|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|InvoiceType|Invoice Type|`string`|20||Required|
|DocumentDate|Document Date|`datetime`|20||Required|
|ValueDate|Value Date|`datetime`|20||Required|
|ReceivedDate|Received Date|`datetime`|20||Required|
|DocumentCurrencyCode|Document Currency|`string`|3||Required|
|NarrativeCurrencyCode|Narrative Currency|`string`|3|||
|FunctionalCurrencyCode|Functional Currency|`string`|3|||
|SecondaryReference|Secondary Reference|`string`|10|||
|DepartmentCode|Department Code|`string`|4|||
|ClientReference|Client Reference|`string`|30|||
|PaymentTermsCode|Payment Terms Code|`string`|8|||
|PaymentModeCode|Payment Mode Code|`string`|1|||


# Data Structures

## 200 SuccessResponse (object)
+ Value: Success (string)

## 200 UpdateResponse (object)
+ Value: Updated (string)

## 200 DeletedResponse (object)
+ Value: Deleted (string)

## 200 AuthoriseResponse (object)
+ Value: Authorised (string)

## 201 CreateResponse (object)
+ Value: Created (string)

## 201 CreateMessages (object)
+ Messages (array [201 ErrorMessageDetail])

## 201 ErrorMessageDetail (object)
+ Severity: Warning (string)
+ Message: `API5084 - LEG : {fieldName} has a {fieldName} of {value}.` (string)

## 201 CreateBllMessages (object)
+ Messages (array [201 ErrorBllMessageDetail])

## 201 ErrorBllMessageDetail (object)
+ Severity: Warning (string)
+ Message: `API5084 - API : {fieldName} has a {fieldName} of {value}.` (string)

## 400 Response (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array [400 ErrorMessageDetail])

## 400 ErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5058 - Data : The mandatory field {fieldName} was missing in the request body.` (string)


## 400 BadPropertyResponse (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array[400 BadPropertyErrorMessageDetail])

## 400 BadPropertyErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5074 - API : The value sent in the querystring variable {Property} is not allowed.` (string)


## 400 BadReadResponse (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array[400 BadReadErrorMessageDetail])

## 400 BadReadErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5075 - API : The value sent in the querystring is not allowed.` (string)


## 400 WarningMessageDetail (object)
+ Severity: Warning (string)
+ Message: `API50xx - Data : The field {fieldName} was not found.` (string)

## 400 InfoMessageDetail (object)
+ Severity: Information (string)
+ Message: `API50xx - Data : Now create xyz.` (string)


## 404 Response (object)
+ Response
    + Value: 404 Not Found (string)
+ Messages (array[404 ErrorMessageDetailMessage])

## 404 ErrorMessageDetailMessage (object)
+ Severity: Warning (string)
+ Message: `API5068 - Data : No records found.` (string)


## 405 Response (object)
+ Response
    + Value: 405 Method Not Allowed (string)
+ Messages (array[405 MethodNotAllowedMessage])

## 405 MethodNotAllowedMessage (object)
+ Severity: Error (string)
+ Message: `API5077 - API : That method is not supported, please check the ITAS API documentation.` (string)

## accessToken (object)
+ Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg 

## AccountDetailsClient (object)
+ AccountCode: POSTEIT.P (string)
+ AccountLedgerType: C (string)
+ ExpenseCode: MISC (string)
+ DepartmentCode: GEN (string)
+ AssociateClientCode: ASSOCCLI.P (string)
+ AmountInDocumentCurrency: `-1.02` (number)
+ AmountInNarrativeCurrency: `-1.20` (number)
+ AmountInFunctionalCurrency: `-1.02` (number)
+ Narrative: STAMPA POSTA 4ONLINE GIU22 (string)
+ SecondaryReference: 3220336229 (string)
+ Memo: Add Memo Here (string)
+ FreeField: 0123456789 (string)
+ PersonalInits: RDG (string)

## AccountDetailsNominal (object)
+ AccountCode: 7150.0080 (string)
+ AccountLedgerType: N (string)
+ ExpenseCode: MISC (string)
+ DepartmentCode: GEN (string)
+ AmountInDocumentCurrency: 0.84 (number)
+ AmountInNarrativeCurrency: 1.04 (number)
+ AmountInFunctionalCurrency: 0.84 (number)
+ Narrative: STAMPA POSTA 4ONLINE GIU22 (string)
+ SecondaryReference: 3220336229 (string)
+ Memo: Add Memo Here (string)
+ FreeField: 0123456789 (string)
+ PersonalInits: RDG (string)

## AccountDetailsVat (object)
+ AccountCode: 2141.0010 (string)
+ AccountLedgerType: N (string)
+ ExpenseCode: MISC (string)
+ DepartmentCode: GEN (string)
+ AmountInDocumentCurrency: 0.18 (number)
+ AmountInNarrativeCurrency: 0.16 (number)
+ AmountInFunctionalCurrency: 0.18 (number)
+ VatCode: 22 (string)
+ Narrative: STAMPA POSTA 4ONLINE GIU22 (string)
+ SecondaryReference: 3220336229 (string)
+ Memo: Add Memo Here (string)
+ FreeField: 0123456789 (string)
+ PersonalInits: RDG (string)

## Cost (object)
+ CostCode: QUALITY (string)
+ CurrencyCode: EUR (string)
+ ExpenseCode: STOCK (string)
+ SupplierCode: UMTRAD.P (string)
+ CostValueInvoiceCcy: `316.25` (number) 
+ CostValueCostCcy: `400.15` (number)

## CreateInvSales (object)
+ ContractId: S00001.000 (string)
+ InvoiceDate: `2022-06-22T00:00:00Z` (string)
+ ValueDate: `2022-06-22T00:00:00Z` (string)
+ Quantity: 700 (number)
+ InvoiceCurrencyCode: GBP (string)
+ InvoiceValue: 7000 (number)
+ VatRateCode: Z (string)
+ VatValue: 140 (number)
+ IsSecure: true (boolean)
+ PaymentMode: P (string)
+ PaymentTermsCode: INV 7D (string)
+ ClientReference: 123B (string)
+ Narrative: 22881 205 per metric ton (string)
+ AuthoriseForPosting: true (boolean)
+ Costs (array [Cost])

## CreateManualInvoice (object)
+ DocumentBody (required, DocumentBody)
+ AccountDetails (required, array [AccountDetailsClient, AccountDetailsVat, AccountDetailsNominal])


## DocumentBody (object)
+ InvoiceType: Purchase (string)
+ DocumentDate: `2022-08-10T00:00:00Z` (string)
+ ValueDate: `2022-08-10T00:00:00Z` (string)
+ ReceivedDate: `2022-08-10T00:00:00Z` (string)
+ DocumentCurrencyCode: EUR (string)
+ NarrativeCurrencyCode: USD (string)
+ FunctionalCurrencyCode: EUR (string)
+ SecondaryReference: 3220336229 (string)
+ DepartmentCode: GEN (string)
+ ClientReference: 3220336229 (string)
+ PaymentTermsCode: 30DFBB (string)
+ PaymentMode: P (string)

## InvoiceRefResponse (object)
+ InvoiceReference: SI2200001


